
%% String Array
A = "Hello {{A}}, " + ...
    "{{# foreach x in X}}" + newline + ...
    "{{#if B}}" + ...
    "{{x}}" + ...
    "{{#end}}" + newline + ...
    "{{#foreach y in Y}}" + ...
    "{{y}}" + ...
    "{{#end}}" + ...
    "{{#end}}!";

%% Data
data = struct(...
    "A","world",...
    "X",["A","B","C"],...
    "B",true,...
    "Y",["D","E"]);

%% Lexer
lexer = TemplateEngine.Lexer(A);

%% Assemble Token List
tokens = TemplateEngine.Token.empty();
while (true)
    token = lexer.nextToken();
    if isempty(token)
        break;
    else
        tokens(end+1) = token;
    end  
end   


%% Sort Nodes
node = TemplateEngine.Node(tokens);


