
%% String Array
A = "Hello {{ A }}," + newline + ...
    "{{# foreach x in X }} " + ...
    "{{#if B}}" + newline + ...
    "{{x}}" + newline + ...
    "{{#end}}" + newline + ...
    "{{# foreach y in Y }}" + newline + ...
    "    {{ y}}" + newline + ...
    "{{#end}}" + newline + ...
    "{{#end}}!";

%% Data
data = struct(...
    "A","world",...
    "X",["A","B","C"],...
    "B",true,...
    "Y",["D","E"]);

%% Lexer
lexer = TemplateEngine.Lexer(A);

%% Assemble Token List
tokens = TemplateEngine.Token.empty();
while (true)
    token = lexer.nextToken();
    if isempty(token)
        break;
    else
        tokens(end+1) = token;
    end  
end   






